MyCompany/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Models;

namespace MyCompany.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class HomeController : Controller
	{
		private readonly DataManager dataManager;

		public HomeController(DataManager dataManager) => this.dataManager = dataManager;

		public IActionResult Index() => View();

		[HttpPost]
		public PartialViewResult Index(AjaxPage Page)
		{
			return Page switch
			{
				AjaxPage.Services => PartialView("ServicesPartial", dataManager.ServiceItems.GetServiceItems()),
				AjaxPage.MainPages => PartialView("MainPagesPartial"),
				AjaxPage.News => PartialView("NewsPartial", dataManager.NewsItems.GetNewsItems()),
				AjaxPage.UsersMessages => PartialView("UsersMessagesPartial", dataManager.TechMessages.GetTechMessages()),
				AjaxPage.NewsReviews => PartialView("NewsReviewsPartial", dataManager.NewsMessages.GetNewsMessages()),
				_ => PartialView("ServicesPartial", dataManager.ServiceItems.GetServiceItems()),
			};
		}
	}
}

MyCompany/Areas/Admin/Controllers/NewsItemsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;
using System;
using System.IO;
using static MyCompany.Service.Extensions;

namespace MyCompany.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class NewsItemsController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment webHostEnvironment;

		public NewsItemsController(DataManager dataManager, IWebHostEnvironment webHostEnvironment)
		{
			this.dataManager = dataManager;
			this.webHostEnvironment = webHostEnvironment;
		}

		public IActionResult Edit(Guid id)
		{
			var entity = id == default ? new NewsItem() : dataManager.NewsItems.GetNewsItemById(id);
			return View(entity);
		}

		[HttpPost]
		public IActionResult Edit(NewsItem model, IFormFile titleImageFile)
		{
			if (ModelState.IsValid)
			{
				if (titleImageFile != null)
				{
					FileManager.Delete(model.TitleImagePath, "images/uploads/", webHostEnvironment);

					model.TitleImagePath = Guid.NewGuid().ToString("N") + titleImageFile.FileName;
					using var stream = new FileStream(Path.Combine(webHostEnvironment.WebRootPath, "images/uploads/", model.TitleImagePath), FileMode.Create);
					titleImageFile.CopyTo(stream);
				}

				try
				{
					dataManager.NewsItems.SaveNewsItem(model);
				}
				catch (Exception ex)
				{
					if (ex.InnerException.Message.Contains("Повторяющееся значение ключа: "))
						ModelState.AddModelError(string.Empty, "Новость уже сущетствует");

					return View(model);
				}
				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}
			return View(model);
		}

		[HttpPost]
		public IActionResult Delete(Guid id)
		{
			FileManager.Delete(dataManager.NewsItems.GetNewsItemById(id).TitleImagePath, "images/uploads/", webHostEnvironment);

			dataManager.NewsItems.DeleteNewsItem(id);
			return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
		}
	}
}

MyCompany/Areas/Admin/Controllers/ServiceItemsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;
using System;
using System.IO;
using static MyCompany.Service.Extensions;

namespace MyCompany.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class ServiceItemsController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment webHostEnvironment;

		public ServiceItemsController(DataManager dataManager, IWebHostEnvironment webHostEnvironment)
		{
			this.dataManager = dataManager;
			this.webHostEnvironment = webHostEnvironment;
		}

		public IActionResult Edit(Guid id)
		{
			var entity = id == default ? new ServiceItem() : dataManager.ServiceItems.GetServiceItemById(id);
			return View(entity);
		}

		[HttpPost]
		public IActionResult Edit(ServiceItem model, IFormFile titleImageFile)
		{
			if (ModelState.IsValid)
			{
				if (titleImageFile != null)
				{
					FileManager.Delete(model.TitleImagePath, "images/uploads/", webHostEnvironment);

					model.TitleImagePath = Guid.NewGuid().ToString("N") + titleImageFile.FileName;
					using var stream = new FileStream(Path.Combine(webHostEnvironment.WebRootPath, "images/uploads/", model.TitleImagePath), FileMode.Create);
					titleImageFile.CopyTo(stream);
				}

				dataManager.ServiceItems.SaveServiceItem(model);

				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}
			return View(model);
		}

		[HttpPost]
		public IActionResult Delete(Guid id)
		{
			FileManager.Delete(dataManager.ServiceItems.GetServiceItemById(id).TitleImagePath, "images/uploads/", webHostEnvironment);

			dataManager.ServiceItems.DeleteServiceItem(id);
			return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
		}
	}
}

MyCompany/Areas/Admin/Controllers/TextFieldsController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class TextFieldsController : Controller
	{
		private readonly DataManager dataManager;

		public TextFieldsController(DataManager dataManager) => this.dataManager = dataManager;

		public IActionResult Edit(string codeWord)
		{
			var entity = dataManager.TextFields.GetTextFieldByCodeWord(codeWord);

			if (codeWord == "PageServices" || codeWord == "PageNews")
				ViewBag.IsText = false;

			return View(entity);
		}

		[HttpPost]
		public IActionResult Edit(TextField model)
		{
			if (ModelState.IsValid)
			{
				dataManager.TextFields.SaveTextField(model);
				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}
			return View(model);
		}
	}
}

MyCompany/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;

namespace MyCompany.Controllers
{
	public class HomeController : Controller
	{
		private readonly DataManager dataManager;

		public HomeController(DataManager dataManager) => this.dataManager = dataManager;

		public IActionResult Index() => View(dataManager.TextFields.GetTextFieldByCodeWord("PageIndex"));

		public IActionResult Contacts() => View(dataManager.TextFields.GetTextFieldByCodeWord("PageContacts"));
	}
}

MyCompany/Areas/Admin/Views/Home/Index.cshtml
@{
    string strTitle = "Панель администратора";
    ViewBag.Title = strTitle;
}


<div>
    <h1>@strTitle</h1>

    <div>
        <label>Выберите страницу для редактирования: </label>
        <select id="adminSelect" name="adminSelect">
            <option value="MainPages">Страницы сайта</option>
            <option value="Services">Наши услуги</option>
            <option value="News">Новости</option>
            <option value="NewsReviews">Рецензии новостей</option>
            <option value="UsersMessages">Сообщения от пользователей</option>
        </select>

        <div id="results"></div>

        <div class="div-box">
            <form asp-area="" asp-controller="Account" asp-action="Logout" method="post">
                <input type="submit" value="Выйти" />
            </form>
        </div>
    </div>
</div>


<script>
    @*function AjaxLoad() {
        $.ajax({
            url: '@Url.Action("Index", "Home", new { Area = "Admin" })',
            data: { Page: $('select#adminSelect').val() },
            type: 'POST',
            success: function (data) {
                $("div#results").html(data);
            }
        });
    }

    let activeOption = document.querySelector('select#adminSelect');
    $('select#adminSelect').change(function () {
        sessionStorage.setItem('ActiveOption', activeOption.value);
        AjaxLoad.call();
    });

    if (window.location.pathname.indexOf('/Admin') == 0 || window.location.pathname.indexOf('/admin') == 0)
    window.onload = () => {
        activeOption.value = sessionStorage.getItem('ActiveOption') ? sessionStorage.getItem('ActiveOption') : 'MainPages';
        AjaxLoad.call();
    };*@

</script>

MyCompany/Areas/Admin/Views/Home/MainPagesPartial.cshtml
<div class="div-box">
    <h3>Редактировать страницы сайта</h3>
    <a style="text-decoration:none; font-weight:bolder;" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageIndex">Главная</a>
    <br /><br />
    <a style="text-decoration:none; font-weight:bolder;" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageNews">Новости</a>
    <br /><br />
    <a style="text-decoration:none; font-weight:bolder;" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageServices">Наши услги</a>
    <br /><br />
    <a style="text-decoration:none; font-weight:bolder;" asp-area="Admin" asp-controller="TextFields" asp-action="Edit" asp-route-codeWord="PageContacts">Контакты</a>
</div>

MyCompany/Areas/Admin/Views/Home/NewsPartial.cshtml
@model IQueryable<NewsItem>

<h3>Новости</h3>
<div class="div-box">
    <a asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="">Добавить новость</a>
</div>
@if (Model.Any())
{
    <div>
        @foreach (NewsItem entity in Model)
        {
        <div>
            <a style="text-decoration:none; font-weight:bolder;" asp-area="" asp-controller="News" asp-action="Index" asp-route-id="@entity.Id">
                @($"{entity.Title}")
            </a>
            <br />
            <a class="div-box" asp-area="Admin" asp-controller="NewsItems" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>

            <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="NewsItems" asp-action="Delete" method="post">
                <input type="hidden" name="id" value="@entity.Id" />
                <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
            </form>
            <br /><br />
        </div>
        }
    </div>
}

MyCompany/Areas/Admin/Views/Home/NewsReviewsPartial.cshtml
@model IQueryable<NewsMessage>

<h3>Рецензии новостей</h3>
@if (Model.Any())
{
    <div>
        @foreach (NewsMessage entity in Model)
        {
            <div>
                <a style="text-decoration:none; font-weight:bolder;" asp-area="Admin" asp-controller="NewsReviews" asp-action="Review" asp-route-id="@entity.Id">
                    @($"{entity.Title}")
                </a>
                <br />

                <a class="div-box" asp-area="Admin" asp-controller="NewsReviews" asp-action="Review" asp-route-id="@entity.Id">Просмотреть</a>

                <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="NewsReviews" asp-action="Delete" method="post">
                    <input type="hidden" name="id" value="@entity.Id" />
                    <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
                </form>

                <br /><br />
            </div>
        }
    </div>
}

MyCompany/Areas/Admin/Views/Home/ServicesPartial.cshtml
@model IQueryable<ServiceItem>

<h3>Наши услуги</h3>
<div class="div-box">
    <a asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="">Добавить услугу</a>
</div>
@if (Model.Any())
{
    <div>
        @foreach (ServiceItem entity in Model)
        {
        <div>
            <a style="text-decoration:none; font-weight:bolder;" asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="@entity.Id">
                @($"{entity.Title}")
            </a>
            <br />
            <a class="div-box" asp-area="Admin" asp-controller="ServiceItems" asp-action="Edit" asp-route-id="@entity.Id">Редактировать</a>

            <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="ServiceItems" asp-action="Delete" method="post">
                <input type="hidden" name="id" value="@entity.Id" />
                <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
            </form>
            <br /><br />
        </div>
        }
    </div>
}

MyCompany/Areas/Admin/Views/Home/UsersMessagesPartial.cshtml
@model IQueryable<TechMessage>

<h3>Сообщения пользователей</h3>
@if (Model.Any())
{
    <div>
        @foreach (TechMessage entity in Model)
        {
            <div>
                <a style="text-decoration:none; font-weight:bolder;" asp-area="Admin" asp-controller="UsersMessages" asp-action="Index" asp-route-id="@entity.Id">
                    @($"{entity.Title}")
                </a>
                <br />
                <a class="div-box" sp-area="Admin" asp-controller="UsersMessages" asp-action="Index" asp-route-id="@entity.Id">Открыть</a>

                <form style="display: inline-block;" id="form-@entity.Id" asp-area="Admin" asp-controller="UsersMessages" asp-action="Delete" method="post">
                    <input type="hidden" name="id" value="@entity.Id" />
                    <a href="#" onclick="document.getElementById('form-@entity.Id').submit();">Удалить</a>
                </form>

                <br />
                <br />
            </div>
        }
    </div>
}