MyCompany/Controllers/NewsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Models;
using MyCompany.Service;
using System;
using System.IO;
using System.Linq;
using static MyCompany.Service.Extensions;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;

namespace MyCompany.Controllers
{
	public class NewsController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment webHostEnvironment;

		public NewsController(DataManager dataManager, IWebHostEnvironment webHostEnvironment)
		{
			this.dataManager = dataManager;
			this.webHostEnvironment = webHostEnvironment;
		}

		public async Task<IActionResult> Index(Guid id, int page = 1)
		{
			if (id != default)
				return View("Show", dataManager.NewsItems.GetNewsItemById(id));

			IQueryable<NewsItem> newsItems = dataManager.NewsItems.GetNewsItems();
			TextField textField = dataManager.TextFields.GetTextFieldByCodeWord("PageNews"); ;

			int pageSize = 4;
			var count = await newsItems.CountAsync();
			var items = await newsItems.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
			PageViewModel pageViewModel = new(count, page, pageSize);

			NewsViewModel newsViewModel = new() { NewsItems = items, TextField = textField, PageViewModel = pageViewModel};

			return View(newsViewModel);
		}

		public IActionResult Add() => View(new NewsMessage());

		[HttpPost]
		public IActionResult Add(NewsMessage newsMessage, IFormFile titleImageFile)
		{
			if (ModelState.IsValid)
			{
				if (titleImageFile != null)
				{
					newsMessage.TitleImagePath = Guid.NewGuid().ToString("N") + titleImageFile.FileName;
					using var stream = new FileStream(Path.Combine(webHostEnvironment.WebRootPath, "images/uploads/", newsMessage.TitleImagePath), FileMode.Create);
						titleImageFile.CopyTo(stream);

				}

				dataManager.NewsMessages.SaveNewsMessage(newsMessage);

				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}

			return View(newsMessage);
		}
	}
}

MyCompany/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace MyCompany.Controllers
{
	public class ServicesController : Controller
	{
		private readonly DataManager dataManager;

		public ServicesController(DataManager dataManager) => this.dataManager = dataManager;

		public async Task<IActionResult> IndexAsync(Guid id, int page = 1)
		{
			if (id != default)
				return View("Show", dataManager.ServiceItems.GetServiceItemById(id));

			IQueryable<ServiceItem> serviceItems = dataManager.ServiceItems.GetServiceItems();
			TextField textField = dataManager.TextFields.GetTextFieldByCodeWord("PageServices");

			int pageSize = 7;
			var count = await serviceItems.CountAsync();
			var items = await serviceItems.Skip((page - 1) * pageSize).Take(pageSize).ToListAsync();
			PageViewModel pageViewModel = new(count, page, pageSize);

			ServiceViewModel serviceViewModel = new() { ServiceItems = items, TextField = textField, PageViewModel = pageViewModel };

			return View(serviceViewModel);
		}
	}
}

MyCompany/Controllers/UserActionsController.cs
using Microsoft.AspNetCore.Mvc;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Service;

namespace MyCompany.Controllers
{
	public class UserActionsController : Controller
	{
		private readonly DataManager dataManager;

		public UserActionsController(DataManager dataManager) => this.dataManager = dataManager;

		public IActionResult TechSupport() => View(new TechMessage());

		[HttpPost]
		public IActionResult Send(TechMessage techMessage)
		{
			if (ModelState.IsValid)
			{
				dataManager.TechMessages.SaveTechMessage(techMessage);
				return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
			}

			return View(techMessage);
		}
	}
}

MyCompany/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/sass.min.css" asp-append-version="true"/>

MyCompany/Views/Shared/FooterPartial.cshtml
<div id="footer-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">

                <div id="copyright">
                    <a asp-area="" asp-controller="UserActions" asp-action="TechSupport">Техническая поддержка</a>
                    <br />
                    <br />
                    &copy; @Config.CompanyName. All rights reserved. | Design: <a href="http://html5up.net">HTML5 UP</a>
                </div>

            </div>
        </div>
    </div>
</div>

MyCompany/Views/Shared/HeaderPartial.cshtml
<div id="header-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <header id="header">
                    <h1><a href="/" id="logo">@Config.CompanyName</a></h1>
                    <nav id="nav">
                        <a asp-area="" asp-controller="Home" asp-action="Index">Главная</a>
                        <a asp-area="" asp-controller="News" asp-action="Index" asp-route-id="">Новости</a>
                        <a asp-area="" asp-controller="Services" asp-action="Index" asp-route-id="">Наши услуги</a>
                        <a asp-area="" asp-controller="Home" asp-action="Contacts">Контакты</a>
                    </nav>
                </header>
            </div>
        </div>
    </div>
</div>

MyCompany/Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
<link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />


@if (ViewBag.Title != null)
{
    <title>@ViewBag.Tite</title>
}
else
{
    <title>@Config.CompanyName</title>
}

@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}

@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

MyCompany/Views/Shared/ScriptsPartial.cshtml
<script src="~/js/scripts.min.js" asp-append-version="true"></script>

MyCompany/Views/Shared/SidebarPartial.cshtml
<div class="col-4 col-12-medium imp-medium">
	<cache>
		@(await Component.InvokeAsync<SidebarViewComponent>())
	</cache>
</div>

MyCompany/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    @{ await Html.RenderPartialAsync("MetatagsPartial");}
    @{ await Html.RenderPartialAsync("CssPartial");}
    

</head>
<body>

    <div id="page-wrapper">
        @{ await Html.RenderPartialAsync("HeaderPartial");}

        <div id="main">
            <div class="container">
                <div class="row main-row">
                    <div class="col-8 col-12-medium">
                        @RenderBody()
                    </div>
                    @RenderSection("sidebar", false)
                </div>
            </div>
        </div>
        @{ await Html.RenderPartialAsync("FooterPartial");}
    </div>
    @{ await Html.RenderPartialAsync("ScriptsPartial");}
</body>
</html>