MyCompany/Areas/Admin/Controllers/NewsReviewsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyCompany.Domain;
using MyCompany.Domain.Entities;
using MyCompany.Models;
using MyCompany.Service;
using System;
using System.IO;
using System.Threading.Tasks;
using static MyCompany.Service.Extensions;

namespace MyCompany.Areas.Admin.Controllers
{
	[Area("Admin")]
	public class NewsReviewsController : Controller
	{
		private readonly DataManager dataManager;
		private readonly IWebHostEnvironment webHostEnvironment;
		private readonly IMailService mailService;
		private readonly ILogger<NewsReviewsController> logger;

		public NewsReviewsController(DataManager dataManager, IWebHostEnvironment webHostEnvironment, IMailService mailService, ILogger<NewsReviewsController> logger)
		{
			this.dataManager = dataManager;
			this.webHostEnvironment = webHostEnvironment;
			this.mailService = mailService;
			this.logger = logger;
		}
		public IActionResult Review(Guid id)
		{
			NewsMessage newsMessage = dataManager.NewsMessages.GetNewsMessageById(id);
			return View(newsMessage);
		}

		// TODO Refactor
		[HttpPost]
		public async Task<IActionResult> Review(NewsMessage newsMessage, IFormFile titleImageFile, string submitButton)
		{
			if (submitButton == "Принять")
			{
				if (ModelState.IsValid)
				{
					FileManager.SaveImage(titleImageFile, newsMessage.TitleImagePath, webHostEnvironment);

					NewsItem newsItem = newsMessage.ConvertToNews();

					try
					{
						dataManager.NewsItems.SaveNewsItem(newsItem);
					}
					catch (Exception ex)
					{
						if (ex.GetBaseException().Message.Contains("Повторяющееся значение ключа: "))
						{
							ModelState.AddModelError(string.Empty, "Новость уже сущетствует");
							return View(newsMessage);
						}
						logger.LogError(ex.GetBaseException().Message);
					}
				}
				else
					return View(newsMessage);
			}

			MailRequest mailRequest = new()
			{
				Subject = new string("Рецензия на новсть: " + newsMessage.Title),
				ToEmail = newsMessage.Email,
				ResponseBody = newsMessage.ResponsetText,
				DateSent = newsMessage.DateAdded,
				UserBody = new string(newsMessage.Subtitle + "" + newsMessage.Text),
				TitleImagePath = Path.Combine(webHostEnvironment.WebRootPath, "images/uploads/", newsMessage.TitleImagePath)
			};
			await mailService.SendEmailAsync(mailRequest);

			dataManager.NewsMessages.DeleteNewsMessage(newsMessage.Id);

			return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
		}

		[HttpPost]
		public IActionResult Delete(Guid id)
		{
			FileManager.Delete(dataManager.NewsMessages.GetNewsMessageById(id).TitleImagePath, "images/uploads/", webHostEnvironment);

			dataManager.NewsMessages.DeleteNewsMessage(id);
			return RedirectToAction(nameof(HomeController.Index), nameof(HomeController).CutController());
		}
	}
}

MyCompany/Areas/Admin/Views/NewsReviews/Review.cshtml
@model NewsMessage
@{
    ViewBag.Title = Model.MetaTitle;
    ViewBag.Description = Model.MetaDescription;
    ViewBag.KeyWords = Model.MetaKeywords;

    string strTitle = "Рецензия на новость";
    ViewBag.Title = strTitle;
}

<h2>@strTitle</h2>
<form asp-area="Admin" asp-controller="NewsReviews" asp-action="Review" method="post" enctype="multipart/form-data">
    <div>
        <input type="hidden" asp-for="Id" />
        <input type="hidden" asp-for="TitleImagePath" />

        <div asp-validation-summary="All"></div>
        <div class="div-box">
            <label asp-for="Title"></label>
            <input asp-for="Title" />
            <span asp-validation-for="Title"></span>
        </div>
        <div class="div-box">
            <label>Дата создания</label>
            <input asp-for="DateAdded" />
            <span asp-validation-for="DateAdded"></span>
        </div>
        <div class="div-box">
            <label asp-for="Subtitle"></label>
            <textarea asp-for="Subtitle" class="editor"></textarea>
            <span asp-validation-for="Subtitle"></span>
        </div>
        <div class="div-box">
            <label asp-for="Text"></label>
            <textarea asp-for="Text" class="editor"></textarea>
            <span asp-validation-for="Text"></span>
        </div>
        <div class="div-box div-image">
            <label asp-for="TitleImagePath"></label>
            <input type="file" name="titleImageFile" id="titleImageFile" />
            <div>
                @if (Model.TitleImagePath != null)
                {
                    <img class="img-block" src="~/images/uploads/@Model.TitleImagePath" />
                }
            </div>
        </div>
        <div class="div-box">
            <label asp-for="MetaTitle"></label>
            <input asp-for="MetaTitle" />
            <span asp-validation-for="MetaTitle"></span>
        </div>
        <div class="div-box">
            <label asp-for="MetaDescription"></label>
            <input asp-for="MetaDescription" />
            <span asp-validation-for="MetaDescription"></span>
        </div>
        <div class="div-box">
            <label asp-for="MetaKeywords"></label>
            <input asp-for="MetaKeywords" />
            <span asp-validation-for="MetaKeywords"></span>
        </div>
    </div>

    <div>

        <br /><br />
        <div class="div-box">
            <label asp-for="Email"></label>
            <input asp-for="Email" readonly />
        </div>
        <div class="div-box">
            <label asp-for="ResponsetText"></label>
            <textarea asp-for="ResponsetText" class="editor"></textarea>
        </div>
        <input type="submit" value="Принять" name="submitButton" />
        <input type="submit" value="Отклонить" name="submitButton" />

    </div>
</form>

<script src="~/js/ckeditor/build/ckeditor.js"></script>
<script>
    var allEditors = document.querySelectorAll('.editor');
    for (var i = 0; i < allEditors.length; ++i) {
        ClassicEditor
            .create(allEditors[i], {

                toolbar: {
                    items: [
                        'undo',
                        'redo',
                        '|',
                        'heading',
                        'fontFamily',
                        'fontSize',
                        'bold',
                        'italic',
                        'underline',
                        'subscript',
                        'superscript',
                        'strikethrough',
                        'link',
                        'fontBackgroundColor',
                        'fontColor',
                        'removeFormat',
                        '|',
                        'insertTable',
                        'horizontalLine',
                        'bulletedList',
                        'numberedList',
                        'outdent',
                        'indent',
                        'alignment',
                        '|',
                        'findAndReplace',
                        'specialCharacters'
                    ]
                },
                language: 'ru',
                table: {
                    contentToolbar: [
                        'tableColumn',
                        'tableRow',
                        'mergeTableCells',
                        'tableCellProperties',
                        'tableProperties'
                    ]
                },
                licenseKey: '',



            })
            .then(editor => {
                window.editor = editor;




            })
            .catch(error => {
                console.error('Oops, something went wrong!');
                console.error('Please, report the following error on https://github.com/ckeditor/ckeditor5/issues with the build id and the error stack trace:');
                console.warn('Build id: xnelco8s2gr-w9ij9xrvtm7e');
                console.error(error);
            });
    }
</script>